config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get "/jobs", to: "jobs#index"

  get "/jobs/new", to: "jobs#new"

  post "/jobs", to: "jobs#create"


  get "/jobs/:id", to: "jobs#show", as: "job"
  get "jobs/:id/edit", to: "jobs#edit", as: "edit_job"
  patch "/jobs/:id", to: "jobs#update"

  delete "jobs/:id", to: "jobs#delete", as: "delete_job"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/job.rb
class Job < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController

  def index
    @jobs = Job.all
  end

  def show
    @job = Job.find_by(params[:id])
  end

  def new
    @job = Job.new
  end

  def create
    @job = Job.new(
    title: params[:job][:title],
    description: params[:job][:description],
    company: params[:job][:company]
    )
    if @job.save
      redirect_to jobs_path
    else
      render :new
    end
  end

  def edit
    @job = Job.find_by(params[:id])
  end

  def update
    @job = Job.find_by(params[:id])
    result = @job.update({
      title: params[:job][:title],
      description: params[:job][:description],
      company: params[:job][:company]
      })
      if result
        redirect_to job_path(@job.id)
      else
        render :edit
      end
  end

  def delete
    job = Job.find_by(params[:id])

    if job.destroy
      redirect_to jobs_path
    else
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/edit.html.erb
<h1>Edit Job</h1>

<p>
  <%= form_for @job do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title %>
    <br />
    <%= f.label :description %>
    <%= f.text_field :description %>
    <br />

    <%= f.label :company %>
    <%= f.text_field :company %>
    <br />

    <%= f.submit %>
  <% end %>
</p>

app/views/jobs/index.html.erb
<h3>Jobs</h3>
<!-- <p>
  Jobs coming soon...
</p> -->

<% @jobs.each do |job| %>
  <div class="job">
    <strong>
      <%= link_to job.title, job_path(job.id) %>
    </strong>
  </div>
<% end %>

<p>
  <%= link_to "Add a New Job", jobs_new_path %>
</p>

app/views/jobs/new.html.erb
<h1>New Job</h1>

<%= form_for @job do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <br />
  <%= f.label :description %>
  <%= f.text_field :description %>
  <br />

  <%= f.label :company %>
  <%= f.text_field :company %>
  <br />

  <%= f.submit %>
<% end %>

app/views/jobs/show.html.erb
<h2>Job Details</h2>

<!-- <p>
  TODO: Add a real job
</p> -->

<div>
  <strong><%= @job.title %></strong> at <%= @job.company %>
  <p>
    <%= @job.description %>
  </p>

  <%= link_to "Edit Job", edit_job_path(@job.id) %>
  <%= link_to "Delete Job", delete_job_path(@job.id), method: :delete %>
  <%= link_to "Back to Index", jobs_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JobBoard</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>